#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/BLAS3/C/0/MKL/sgemm/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Measurment of sgemm performance
#####################################################################

 # Kernel iterates over PROBLEMLIST
export MKL_NUM_THREADS=${BENCHIT_NUM_THREADS_PER_PROCESS}
 BENCHIT_KERNEL_PROBLEMLIST="1-12000/1"
