#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2011-01-27 fschmitt $
# $URL: svn+ssh://benchit@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/numerical/BLAS3/C/CUDA/CUBLAS/dgemm/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Measurement of Nvidia CUBLAS dgemm performance
#####################################################################

 # Kernel iterates over PROBLEMLIST
 BENCHIT_KERNEL_PROBLEMLIST="31-16384/31"


ONE="1"
if [ -n "${BENCHIT_NUM_GPUS}" ]; then
if [ ${BENCHIT_NUM_GPUS} -lt ${ONE} ]; then
BENCHIT_NUM_GPUS=1
fi
fi
