#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# $Id: PARAMETERS 1 2009-09-11 12:26:19Z william $
# $URL: svn+ssh://william@rupert.zih.tu-dresden.de/svn-base/benchit-root/BenchITv6/kernel/memory/latencies/C/0/0/pointerchasing/PARAMETERS $
# For license details see COPYING in the package base directory
#####################################################################
# Kernel: Memory Access Time (C)
#####################################################################

 # BENCHIT_KERNEL_MIN_ACCESS_LENGTH is the minimum of accessed memory (in KByte)
 BENCHIT_KERNEL_MIN_ACCESS_LENGTH=1

 # BENCHIT_KERNEL_MAX_ACCESS_LENGTH is the maximum of accessed memory (in KByte)   
 BENCHIT_KERNEL_MAX_ACCESS_LENGTH=51200

 # BENCHIT_KERNEL_ACCESS_STEPS is the number of measurement points
 BENCHIT_KERNEL_ACCESS_STEPS=500

 # BENCHIT_KERNEL_NUMBER_OF_JUMPS is the number of pointer jumps
 # that the kernel will perform per measurement   
 # point (must be a multiple of 100)              
 BENCHIT_KERNEL_NUMBER_OF_JUMPS=400000
 
 # BENCHIT_KERNEL_CACHELINE_SIZE defines the cache line size in Byte
 # default 128
 # it should also handle adjacent line prefetchers, thats why the default
 # is twice the cacheline size (128 instead of 64)
 BENCHIT_KERNEL_CACHELINE_SIZE=128
 
 # BENCHIT_KERNEL_USE_HUGE_PAGES defines whether huge pages should be used or
 # not: 1 enabled, 0: disabled
 # Has also to be declared at COMPILE TIME if it should be used!
 # If Compiled with 1 and run with set to 1, the memory will be allocated with
 # mmap/madvise instead of malloc
 BENCHIT_KERNEL_USE_HUGE_PAGES=1
